### ISSUE TITLE
Problem with accented filepaths on Windows

### ISSUE THREAD

**Issue by SzieberthAdam** [gvellut/FreehandRasterGeoreferencer#4]
```
Traceback (most recent call last):
  File "C:/Documents and Settings/ti2/.qgis2/python/plugins\FreehandRasterGeoreferencer\freehandrastergeoreferencer.py", line 190, in addLayer
    self.createFreehandRasterGeoreferencerLayer()
  File "C:/Documents and Settings/ti2/.qgis2/python/plugins\FreehandRasterGeoreferencer\freehandrastergeoreferencer.py", line 194, in createFreehandRasterGeoreferencerLayer
    imagePath = utils.toRelativeToQGS(imagePath)
  File "C:/Documents and Settings/ti2/.qgis2/python/plugins\FreehandRasterGeoreferencer\utils.py", line 26, in toRelativeToQGS
    qDebug(imagePath)
TypeError: qDebug(str): argument 1 has unexpected type 'unicode'
```

**Comment by SzieberthAdam** [comment]
I believe `qDebug(imagePath.encode('utf8'))` would fix the issue.

**Comment by SzieberthAdam** [comment]
It does.

**Comment by gvellut** [comment]
Thanks! Fixed.
